//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.order_products = new HashSet<order_products>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int cid { get; set; }
        public decimal price { get; set; }
        public int qty { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> createdat { get; set; }
        public string createdby { get; set; }
        public Nullable<System.DateTime> updatedat { get; set; }
        public string updatedby { get; set; }
        public string deletedby { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_products> order_products { get; set; }
    }
}
